AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - Gemfile
    - Guardfile
    - Rakefile
    - vendor/**/*
  UseCache: false

Layout/AccessModifierIndentation:
  IndentationWidth: 2
Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: true
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: true
Lint/EmptyWhen:
  Enabled: false
Lint/LiteralInInterpolation:
  Enabled: false
Lint/RedundantRequireStatement:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - Rakefile
    - "**/*.rake"
    - "**/*_test.rb"
    - "**/*_spec.rb"
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Max: 150
Metrics/MethodLength:
  Max: 15
Metrics/ModuleLength:
  CountComments: false
  Max: 200
  Enabled: true
Metrics/ParameterLists:
  Enabled: true
  Max: 6
Metrics/PerceivedComplexity:
  Max: 10
Naming/AccessorMethodName:
  Enabled: false
Naming/FileName:
  Enabled: false
  Exclude: []
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/PredicateName:
  Enabled: true
  NamePrefix:
    - is_
    - has_
    - have_
  ForbiddenPrefixes:
    - is_
  Exclude:
    - spec/**/*
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/Alias:
  Enabled: false
Style/AndOr:
  EnforcedStyle: conditionals
Style/ClassAndModuleChildren:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    detect: find
    find_all: select
    length: size
Style/CommentedKeyword:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/IfUnlessModifier:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Next:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 9
Style/NumericPredicate:
  Enabled: false
Style/OneLineConditional:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
  EnforcedStyle: exploded
Style/RegexpLiteral:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/Send:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
  AllowIfMethodIsEmpty: true
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
Style/VariableInterpolation:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/WordArray:
  Enabled: false
