inherit_from:
  - vendor/hound/config/style_guides/ruby.yml

# Rails cops
AllCops:
  RunRailsCops: false

# Files you want to exclude
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - db/schema.rb
    - Gemfile
    - Guardfile
    - Rakefile

# TODO: put your overrides here:
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true
