name: Development

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows

        ruby:
          - 2.7
          - "3.0" # quotes ensure this isn't misinterpreted as Integer 3: https://github.com/actions/runner/issues/849
          - 3.1
          - 3.2
          - 3.3
          - 3.4
          - "4.0"

        experimental: [false]
        env: [""]

        include:
          - os: macos
            ruby: truffleruby-head
            experimental: true
          - os: ubuntu
            ruby: truffleruby-head
            experimental: true
          - os: ubuntu
            ruby: jruby
            experimental: true
          - os: ubuntu
            ruby: head
            experimental: true

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
    - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true

    - name: Run tests
      timeout-minutes: 6
      run: |
        ${{matrix.env}} bundle exec rspec

  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
    - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Run rubocop
      timeout-minutes: 6
      run: |
        bundle exec rake rubocop
